"use client";

import { SessionProvider } from "next-auth/react";
import { createContext, useContext, useState, useEffect } from 'react';

type SupportedLang = 'cs' | 'sk' | 'en';
type TranslationKey = keyof typeof translations['cs'];

const translations: Record<SupportedLang, Record<string, string>> = {
  cs: {
    home: 'Domů',
    map: 'Mapa',
    blog: 'Blog',
    about: 'O projektu',
    login: 'Přihlásit',
    register: 'Registrovat',
    logout: 'Odhlásit',
    welcome: 'Vítejte',
    find_containers: 'Najít kontejnery',
    eco_community: 'Připojte se k naší eko komunitě',
    share_experience: 'Sdílejte své zkušenosti s tříděním odpadu a inspirujte ostatní k ekologickému chování',
    interactive_map: 'Interaktivní mapa',
    find_nearest: 'Najděte nejbližší kontejnery na tříděný odpad ve vašem okolí',
    current_status: 'Aktuální stav',
    info_fill: 'Informace o naplnění kontejnerů od ostatních uživatelů',
    eco_community_tile: 'Eko komunita',
    share_tips: 'Sdílejte tipy a nápady s ostatními ekologicky smýšlejícími lidmi',
    search: 'Vyhledávání',
    waste_type: 'Typ odpadu',
    select_waste: 'Vyberte typ odpadu',
    waste_plast: 'Plast',
    waste_papir: 'Papír',
    waste_sklo: 'Sklo',
    waste_kov: 'Kov',
    waste_bio: 'Bioodpad',
    location: 'Lokace',
    enter_address: 'Zadejte adresu...',
    search_btn: 'Hledat',
    loading_map: 'Načítání mapy...',
    our_mission: 'Naše mise',
    mission_text1: 'Projekt "Kam s tím?" vznikl s cílem zjednodušit třídění odpadu a podpořit udržitelný životní styl. Věříme, že každý malý krok k lepšímu životnímu prostředí má smysl.',
    mission_text2: 'Naším cílem je vytvořit komunitu lidí, kteří se aktivně zajímají o životní prostředí a chtějí přispět k jeho ochraně.',
    what_we_offer: 'Co nabízíme',
    interactive_map_tile: 'Interaktivní mapa kontejnerů',
    find_nearest_tile: 'Najděte nejbližší kontejnery na tříděný odpad ve vašem okolí',
    current_info: 'Aktuální informace',
    share_info: 'Sdílejte a získávejte informace o stavu kontejnerů',
    eco_community_about: 'Eko komunita',
    share_tips_about: 'Sdílejte tipy a nápady s ostatními ekologicky smýšlejícími lidmi',
    contact: 'Kontakt',
    contact_text: 'Máte nějaké otázky nebo návrhy? Neváhejte nás kontaktovat!',
    email: 'Email',
    phone: 'Telefon',
    no_posts: 'Zatím nejsou žádné příspěvky. Buďte první, kdo něco napíše!',
    new_post: 'Nový příspěvek',
    create_post: 'Vytvořit nový příspěvek',
    post_title: 'Název příspěvku',
    post_content: 'Obsah příspěvku',
    cancel: 'Zrušit',
    publish: 'Publikovat',
    author: 'Autor',
    replies: 'Odpovědi',
    no_replies: 'Zatím nejsou žádné odpovědi.',
    write_reply: 'Napište odpověď...',
    send_reply: 'Odeslat odpověď',
    loading: 'Načítání...',
    edit: 'Upravit',
    delete: 'Smazat',
    save: 'Uložit',
    reply: 'Odpovědět',
    like: 'To se mi líbí',
    love: 'Super',
    laugh: 'Směju se',
    wow: 'Překvapení',
    sad: 'Smutné',
    angry: 'Angry',
    invalid_credentials: 'Neplatné přihlašovací údaje',
    something_wrong: 'Něco se pokazilo',
    email_exists: 'Email již existuje',
    no_account: 'Nemáte účet?',
    have_account: 'Již máte účet?',
    password: 'Heslo',
    name: 'Jméno',
    full_name: 'Celé jméno',
  },
  sk: {
    home: 'Domov',
    map: 'Mapa',
    blog: 'Blog',
    about: 'O projekte',
    login: 'Prihlásiť sa',
    register: 'Registrovať',
    logout: 'Odhlásiť sa',
    welcome: 'Vitajte',
    find_containers: 'Nájsť kontajnery',
    eco_community: 'Pripojte sa k našej eko komunite',
    share_experience: 'Zdieľajte svoje skúsenosti s triedením odpadu a inšpirujte ostatných k ekologickému správaniu',
    interactive_map: 'Interaktívna mapa',
    find_nearest: 'Nájdite najbližšie kontajnery na triedený odpad vo vašom okolí',
    current_status: 'Aktuálny stav',
    info_fill: 'Informácie o naplnení kontajnerov od ostatných používateľov',
    eco_community_tile: 'Eko komunita',
    share_tips: 'Zdieľajte tipy a nápady s ostatnými ekologicky zmýšľajúcimi ľuďmi',
    search: 'Vyhľadávanie',
    waste_type: 'Typ odpadu',
    select_waste: 'Vyberte typ odpadu',
    waste_plast: 'Plast',
    waste_papir: 'Papír',
    waste_sklo: 'Sklo',
    waste_kov: 'Kov',
    waste_bio: 'Bioodpad',
    location: 'Lokalita',
    enter_address: 'Zadajte adresu...',
    search_btn: 'Hľadať',
    loading_map: 'Načítanie mapy...',
    our_mission: 'Naša misia',
    mission_text1: 'Projekt "Kam s tým?" vznikol s cieľom zjednodušiť triedenie odpadu a podporiť udržateľný životný štýl. Veríme, že každý malý krok k lepšiemu životnému prostrediu má zmysel.',
    mission_text2: 'Naším cieľom je vytvoriť komunitu ľudí, ktorí sa aktívne zaujímajú o životné prostredie a chcú prispieť k jeho ochrane.',
    what_we_offer: 'Čo ponúkame',
    interactive_map_tile: 'Interaktívna mapa kontajnerov',
    find_nearest_tile: 'Nájdite najbližšie kontajnery na triedený odpad vo vašom okolí',
    current_info: 'Aktuálne informácie',
    share_info: 'Zdieľajte a získavajte informácie o stave kontajnerov',
    eco_community_about: 'Eko komunita',
    share_tips_about: 'Zdieľajte tipy a nápady s ostatnými ekologicky zmýšľajúcimi ľuďmi',
    contact: 'Kontakt',
    contact_text: 'Máte nejaké otázky alebo návrhy? Neváhajte nás kontaktovať!',
    email: 'Email',
    phone: 'Telefón',
    no_posts: 'Zatiaľ nie sú žiadne príspevky. Buďte prvý, kto niečo napíše!',
    new_post: 'Nový príspevok',
    create_post: 'Vytvoriť nový príspevok',
    post_title: 'Názov príspevku',
    post_content: 'Obsah príspevku',
    cancel: 'Zrušiť',
    publish: 'Publikovať',
    author: 'Autor',
    replies: 'Odpovede',
    no_replies: 'Zatiaľ nie sú žiadne odpovede.',
    write_reply: 'Napíšte odpoveď...',
    send_reply: 'Odoslať odpoveď',
    loading: 'Načítanie...',
    edit: 'Upraviť',
    delete: 'Vymazať',
    save: 'Uložiť',
    reply: 'Odpovedať',
    like: 'Páči sa mi to',
    love: 'Super',
    laugh: 'Smejem sa',
    wow: 'Prekvapenie',
    sad: 'Smutné',
    angry: 'Nahnevaný',
    invalid_credentials: 'Neplatné prihlasovacie údaje',
    something_wrong: 'Niečo sa pokazilo',
    email_exists: 'Email už existuje',
    no_account: 'Nemáte účet?',
    have_account: 'Už máte účet?',
    password: 'Heslo',
    name: 'Meno',
    full_name: 'Celé meno',
  },
  en: {
    home: 'Home',
    map: 'Map',
    blog: 'Blog',
    about: 'About',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    welcome: 'Welcome',
    find_containers: 'Find containers',
    eco_community: 'Join our eco community',
    share_experience: 'Share your waste sorting experience and inspire others to eco-friendly behavior',
    interactive_map: 'Interactive map',
    find_nearest: 'Find the nearest sorted waste containers near you',
    current_status: 'Current status',
    info_fill: 'Container fill information from other users',
    eco_community_tile: 'Eco community',
    share_tips: 'Share tips and ideas with other eco-minded people',
    search: 'Search',
    waste_type: 'Waste type',
    select_waste: 'Select waste type',
    waste_plast: 'Plastic',
    waste_papir: 'Paper',
    waste_sklo: 'Glass',
    waste_kov: 'Metal',
    waste_bio: 'Biowaste',
    location: 'Location',
    enter_address: 'Enter address...',
    search_btn: 'Search',
    loading_map: 'Loading map...',
    our_mission: 'Our mission',
    mission_text1: 'The "Kam s tím?" project was created to simplify waste sorting and support a sustainable lifestyle. We believe every small step towards a better environment matters.',
    mission_text2: 'Our goal is to create a community of people who are actively interested in the environment and want to help protect it.',
    what_we_offer: 'What we offer',
    interactive_map_tile: 'Interactive container map',
    find_nearest_tile: 'Find the nearest sorted waste containers near you',
    current_info: 'Current information',
    share_info: 'Share and get information about container status',
    eco_community_about: 'Eco community',
    share_tips_about: 'Share tips and ideas with other eco-minded people',
    contact: 'Contact',
    contact_text: 'Do you have any questions or suggestions? Do not hesitate to contact us!',
    email: 'Email',
    phone: 'Phone',
    no_posts: 'No posts yet. Be the first to write something!',
    new_post: 'New post',
    create_post: 'Create new post',
    post_title: 'Post title',
    post_content: 'Post content',
    cancel: 'Cancel',
    publish: 'Publish',
    author: 'Author',
    replies: 'Replies',
    no_replies: 'No replies yet.',
    write_reply: 'Write a reply...',
    send_reply: 'Send reply',
    loading: 'Loading...',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    reply: 'Reply',
    like: 'Like',
    love: 'Love',
    laugh: 'Laugh',
    wow: 'Wow',
    sad: 'Sad',
    angry: 'Angry',
    invalid_credentials: 'Invalid credentials',
    something_wrong: 'Something went wrong',
    email_exists: 'Email already exists',
    no_account: "Don't have an account?",
    have_account: 'Already have an account?',
    password: 'Password',
    name: 'Name',
    full_name: 'Full name',
  },
};

const TranslationContext = createContext({
  lang: 'cs',
  setLang: (lang: string) => {},
  t: (key: string) => key,
});

export function TranslationProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState('cs');

  useEffect(() => {
    const stored = localStorage.getItem('lang');
    if (stored && ['cs', 'sk', 'en'].includes(stored)) setLang(stored);
  }, []);

  const changeLang = (l: string) => {
    setLang(l);
    localStorage.setItem('lang', l);
  };

  const t = (key: string) => translations[lang as SupportedLang][key] || key;

  return (
    <TranslationContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </TranslationContext.Provider>
  );
}

export function useTranslation() {
  return useContext(TranslationContext);
}

export function Providers({ children }: { children: React.ReactNode }) {
  return (
    <SessionProvider>
      <TranslationProvider>{children}</TranslationProvider>
    </SessionProvider>
  );
} 